#
# https://gist.github.com/DevoKun/01b6c9963d5508579f4cbd75d52640a9
#

version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - default
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:4:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
    default:
        driver: bridge 
    scorpio-proxy-net:
        name: scorpio_network
    new-scorpio-net-end:
        name: scorpio_network_end

#docker-compose -f docker-compose-single-broker.yml up -d